server {
    listen 80;
    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ @router;
    }

    location @router {
        rewrite ^/(.*)$ /index.php?a=$1 last;
    }

    location ~ \.php$ {

        # если файла php нет И это не index.php
        if (!-f $document_root$fastcgi_script_name) {
            rewrite ^/(?!index\.php)(.*)$ /index.php?a=$1 last;
        }

        fastcgi_pass php:9000;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}